spring:
    http:
        encoding:
          charset: UTF-8
          enabled: true
          force: true
    freemarker:
        allowRequestOverride: false
        allowSessionOverride: false
        cache: true
        checkTemplateLocation: true
        contentType: text/html
        exposeRequestAttributes: false
        exposeSessionAttributes: false
        exposeSpringMacroHelpers: false
        suffix: .ftl
        templateEncoding: UTF-8
        templateLoaderPath: classpath:/templates/  #表示所有的模板文件都放在该目录下
        spring.freemarker.settings:
           locale: zh_CN
           date_format: yyyy-MM-dd
           time_format: HH:mm:ss
           datetime_format: yyyy-MM-dd HH:mm:ss
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/assistant?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20
    servlet:
      multipart:
        max-request-size: 102400000
        max-file-size: 102400000
    mvc:
      static-path-pattern: /**
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${upload.path}


mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.cdtc.student.assistant.model

mapper:
    mappers: com.cdtc.student.assistant.dao
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

#==================== logging Setting =====================#
logging:
  level:
    org.springframework: debug
    file: /user/service/log.log
server:
  port: 8087
upload:
  path: /user/service/img